remote_theme: "mmistakes/minimal-mistakes"

# Site Settings
locale                   : "en-US"
title                    : "One Game Documentations"

# Reading Files
include:
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "docs"
