remote_theme: "mmistakes/minimal-mistakes"

# Reading Files
include:
  - _pages

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "docs"
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
